"""added token stuff and date created to User model

Revision ID: 75960b3a9538
Revises: bf91c635a084
Create Date: 2021-11-30 20:42:28.900328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75960b3a9538'
down_revision = 'bf91c635a084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'date_created')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
